### ISSUE TITLE
Unable to access test website

### ISSUE THREAD

**Issue by mehulgit** [akshata29/chatpdf#37]
I am unable to access the test website, the error is shown below:

Request Id: 78953c7f-0344-4f83-b341-6518c8143001
Correlation Id: be6d5db1-d5fb-4e2a-ab79-0b4057d8e053
Timestamp: 2023-08-08T22:24:35Z
Message: AADSTS50020: User account 'mehul@infinity-services.com' from identity provider 'live.com' does not exist in tenant 'Contoso' and cannot access the application 'cbbe9727-b1ae-4fae-a6c7-656f3643721f'(dataaipdfchatauth) in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account.

**Comment by akshata29** [comment]
@mehulgit  - Currently it's by design.  The deployment is now using the authentication and is secured by default to allow access only to the users who are in that tenant.  At this point you will have to run locally or you will need to deploy the app into Azure.  I will be though adding the detail product/feature guide soon to show the product more of as screenshot.
